package main

import (
	"go-example/example"
)

func main() {
	// example.ArraysFunc()
	// example.MapFunc()
	// example.RangeFunc()
	// example.FunctionFunc()
	// example.ClosuresFunc()
	// example.RecursionFunc()
	// example.PointersFunc()
	// example.StructsFunc()
	// example.MethodsFunc()
	// example.MethodsFunc2()
	// example.InterfaceFunc()
	// example.ErrorFunc()
	// example.GoroutineFunc()
	// example.ChannelFunc()
	// example.ChannelBufferFunc()
	// example.ChannelSynchronizationFunc()
	// example.ChannelDirectionsFunc()
	// example.ChannelSelectFunc()
	// time go run main.go 查看运行时间
	// example.TimeoutsFunc()
	// example.NonBlockingChannelOperationsFunc()
	// example.ChannelCloseFunc()
	// example.ChannelRangeFunc()
	// example.TimerFunc()
	// example.TickersFunc()
	// example.WorkerPoolsFunc()
	// example.RateLimitingFunc()
	// example.AtomicCountersFunc()
	// example.MutexesFunc()
	// example.StatefulGoroutinesFunc()
	// example.SortFunc()
	// example.SortByFunc()
	// example.GoPanicFunc()
	// example.GoDeferFunc()
	// example.CollectionFunc()
	// example.StringFunc()
	// example.RegularExpressionsFunc()
	// example.JsonFunc()
	// example.TimeFunc()
	// example.EpochFunc()
	// example.TimeFormat()
	// example.RandFunc()
	// example.NumberParsingFunc()
	example.UrlParse()

}
